version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-livros
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: livrosdb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
