create table assunto
(
    cod       integer generated by default as identity,
    descricao varchar(40) not null,
    primary key (cod)
);

create table autor
(
    cod  integer generated by default as identity,
    nome varchar(40) not null,
    primary key (cod)
);

create table livro
(
    cod            integer generated by default as identity,
    ano_publicacao varchar(4)  not null,
    edicao         integer     not null,
    editora        varchar(40) not null,
    isbn           varchar(13) not null,
    titulo         varchar(40) not null,
    valor          integer     not null,
    primary key (cod)
);

create table livro_assunto
(
    cod         integer generated by default as identity,
    assunto_cod integer not null,
    livro_cod   integer not null,
    primary key (cod)
);

create table livro_autor
(
    cod       integer generated by default as identity,
    autor_cod integer not null,
    livro_cod integer not null,
    primary key (cod)
);

alter table if exists assunto
    add constraint UKnupysjx8ib2c19dr58llnn3lt unique (descricao);

alter table if exists autor
    add constraint UK8yf2pjvxicd298qrpdmwyq5hv unique (nome);

alter table if exists livro
    add constraint UK8yf2pjthrpd298qrpdmwyq5hv unique (isbn);

alter table if exists livro_assunto
    add constraint UK47yhq6c06vsb2ii1omjd0mwws unique (livro_cod, assunto_cod);

alter table if exists livro_assunto
    add constraint FKhops8tkgjmmutmgisoq77e117
    foreign key (assunto_cod)
    references assunto;

alter table if exists livro_assunto
    add constraint FKep779r7skcj6oklqlxha915b4
    foreign key (livro_cod)
    references livro;

alter table if exists livro_autor
    add constraint UK26quu6bpqi7232treca535341 unique (livro_cod, autor_cod);

alter table if exists livro_autor
    add constraint FKswlt3v29xgpm785evndli8j15
    foreign key (autor_cod)
    references autor;

alter table if exists livro_autor
    add constraint FK7txm5cupg3f1lew6cbpbuoxcw
    foreign key (livro_cod)
    references livro;
